### ISSUE TITLE
editorconfig missing comma

### ISSUE THREAD

**Issue by ghost** [cedaro/wp-theme-config#1]
Hello,

Could you tell if the missing comma after `.jshintnoderc` was intended this way, or I'm overlooking something somewhere?

``` editorconfig
[{.jscsrc,.jshintrc,.jshintnoderc*.json,*.yml}]
```

https://github.com/cedaro/cedaro-wp-theme-config/blob/develop/.editorconfig#L16

**Comment by bradyvercher** [comment]
Nope, that wasn't intended. Thanks for the heads up!

**Comment by ghost** [comment]
Thanks :+1:
